version: "2"

services:
  # Behat
  behat:
    hostname: behat
    image: ${BEHAT_IMAGE:-docksal/behat}
    volumes:
      - .:/src
    # Run a built-in web server for access to HTML reports
    ports:
     - 8000:8000
    entrypoint: "php -S 0.0.0.0:8000"
  # Selenium
  browser:
    hostname: browser
    # Pick/uncomment one
    # v3.141.59 for both chrome and firefox were tested and work.
    image: ${SELENIUM_IMAGE:-selenium/standalone-chrome-debug:3.141.59}
    #image: ${SELENIUM_IMAGE:-selenium/standalone-firefox-debug:3.141.59}
    volumes:
      # Workaround to avoid the browser crashing inside a docker container
      # See https://github.com/SeleniumHQ/docker-selenium#quick-start
      - /dev/shm:/dev/shm
    # VNC port for debugging
    # Host: <your-docker-host>:5900 (e.g, localhost:5900, 192.168.64.100:5900)
    # Password: secret
    ports:
      - 5900:5900
